print("Operadores de comparacion")
numero1 = float(input("Primer numero: "))
numero2 = float(input("Segundo numero: "))
print(numero1, "==", numero2, numero1==numero2)
print(numero1, "!=", numero2, numero1!=numero2)
print(numero1, ">", numero2, numero1>numero2)
print(numero1, "<", numero2, numero1<numero2)
print(numero1, ">=", numero2, numero1>=numero2)
print(numero1, "<=", numero2, numero1<=numero2)